nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5173']
        allow_credentials: false
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']
        max_age: 3600
    paths:
        '^/api/': ~
